# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: jaffle_shop
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: default

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: [dbt/models]
seed-paths: [dbt/seeds]
test-paths: [dbt/tests]
analysis-paths: [dbt/analysis]
macro-paths: [dbt/macros]
snapshot-paths: [dbt/snapshots]

target-path: dbt/target  # directory which will store compiled SQL files
clean-targets:       # directories to be removed by `dbt clean`
  - dbt/target
  - dbt/dbt_packages
  - dbt/logs

# Configuring models
models:
  jaffle_shop:
    # Applies to all files under models/marts/core
    marts:
      +materialized: table
    staging:
      +materialized: view