services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: $DBT_POSTGRES_USER_DEV
      POSTGRES_PASSWORD: $DBT_POSTGRES_PWD_DEV
      POSTGRES_DB: $DBT_POSTGRES_DBNAME_DEV
    volumes:
      # Scripts to run when DB initialized 1st time
      - ./db_setup:/docker-entrypoint-initdb.d
      # Raw data files to load when init
      - ./raw_data:/input_data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dbt"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - $DBT_POSTGRES_PORT_DEV:5432
