config:
  send_anonymous_usage_stats: False

dbt_sample_app:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: dbt
      password: password1234
      dbname: dbt_sample_app
      schema: warehouse